### PR TITLE
Security Fix and Code Coverage

### LINKED ISSUE #31: Security: Users can see view other users' profiles, including password hash
**Steps to reproduce:**
1. Using your browser, login as 'user@user.com'
2. Go to /users/1
3. Assuming 1 is the id of the admin, you will see the profile of the admin including the password hash. 

**Previous behavior:**

I checked in version 1 of L4withSentry and it looks like the system properly handled this condition by showing an error that you do not have access to the user.

**Notes:**

It looks like the problem lies on lines [49 and 50](https://github.com/rydurham/L4withSentry/commit/af97a7a6383660e929aa97be174e2e2ee0f2e15c#diff-0ad2286fb1ab9c8b1ec84d26853bf8f1R49) of app/controllers/UserController.php where the filters are applied to resource methods. The show and update resource methods did not have the inGroup:Admins filter applied.

### PR DESCRIPTION
**Pull request by jimthedev**
Fixes #31 - Security issue with filters on User Controller
Adds code coverage config for Scrutinizer

### CODE REVIEW

**Comment by rydurham** [comment]
I understand the benefit of using sqlite for testing, but I don't understand what we gain by changing the 'default' db setting - can you clarify?

**Comment by jimthedev** [comment]
Sure, this is a new config file that is specific to the testing environment. The default setting only applies when tests are run.  Laravel is smart enough to look only at the testing environment and configs. Laravel will still use mysql as set in config/database.php for anything other than when tests are run.

**Comment by rydurham** [comment]
Ah - yes.  I missed that it was a change to 'app/config/testing/database.php' rather than 'app/config/database.php'. 

Thanks for catching that security issue!

**Comment by jimthedev** [comment]
Sure thing. Thanks for the merge!

**Pull request merged**
